#!/bin/sh -e

libdir="/home/wfan/owl/targets/apache/nghttp2-1.26.0/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/home/wfan/owl/targets/apache/nghttp2-1.26.0/lib/includes -I/home/wfan/owl/targets/apache/nghttp2-1.26.0/lib/includes"
export CGO_LDFLAGS="-L$libdir"
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
