# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shixiong/owl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shixiong/owl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shixiong/owl/CMakeFiles /home/shixiong/owl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shixiong/owl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Inst2Int

# Build rule for target.
Inst2Int: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Inst2Int
.PHONY : Inst2Int

# fast build rule for target.
Inst2Int/fast:
	$(MAKE) -f lib/Misc/Inst2Int/CMakeFiles/Inst2Int.dir/build.make lib/Misc/Inst2Int/CMakeFiles/Inst2Int.dir/build
.PHONY : Inst2Int/fast

#=============================================================================
# Target rules for targets named CDG

# Build rule for target.
CDG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CDG
.PHONY : CDG

# fast build rule for target.
CDG/fast:
	$(MAKE) -f lib/CDG/CMakeFiles/CDG.dir/build.make lib/CDG/CMakeFiles/CDG.dir/build
.PHONY : CDG/fast

#=============================================================================
# Target rules for targets named SyncLoop

# Build rule for target.
SyncLoop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SyncLoop
.PHONY : SyncLoop

# fast build rule for target.
SyncLoop/fast:
	$(MAKE) -f lib/SyncLoop/CMakeFiles/SyncLoop.dir/build.make lib/SyncLoop/CMakeFiles/SyncLoop.dir/build
.PHONY : SyncLoop/fast

#=============================================================================
# Target rules for targets named DOL

# Build rule for target.
DOL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DOL
.PHONY : DOL

# fast build rule for target.
DOL/fast:
	$(MAKE) -f lib/DOL/CMakeFiles/DOL.dir/build.make lib/DOL/CMakeFiles/DOL.dir/build
.PHONY : DOL/fast

#=============================================================================
# Target rules for targets named ConAnalysis

# Build rule for target.
ConAnalysis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConAnalysis
.PHONY : ConAnalysis

# fast build rule for target.
ConAnalysis/fast:
	$(MAKE) -f lib/ConAnal/CMakeFiles/ConAnalysis.dir/build.make lib/ConAnal/CMakeFiles/ConAnalysis.dir/build
.PHONY : ConAnalysis/fast

#=============================================================================
# Target rules for targets named libsafe-cve-1125

# Build rule for target.
libsafe-cve-1125: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsafe-cve-1125
.PHONY : libsafe-cve-1125

# fast build rule for target.
libsafe-cve-1125/fast:
	$(MAKE) -f TESTS/libsafe-cve-1125/CMakeFiles/libsafe-cve-1125.dir/build.make TESTS/libsafe-cve-1125/CMakeFiles/libsafe-cve-1125.dir/build
.PHONY : libsafe-cve-1125/fast

#=============================================================================
# Target rules for targets named libvirt-cve-1447

# Build rule for target.
libvirt-cve-1447: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvirt-cve-1447
.PHONY : libvirt-cve-1447

# fast build rule for target.
libvirt-cve-1447/fast:
	$(MAKE) -f TESTS/libvirt-cve-1447/CMakeFiles/libvirt-cve-1447.dir/build.make TESTS/libvirt-cve-1447/CMakeFiles/libvirt-cve-1447.dir/build
.PHONY : libvirt-cve-1447/fast

#=============================================================================
# Target rules for targets named apache-21287

# Build rule for target.
apache-21287: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apache-21287
.PHONY : apache-21287

# fast build rule for target.
apache-21287/fast:
	$(MAKE) -f TESTS/apache-21287/CMakeFiles/apache-21287.dir/build.make TESTS/apache-21287/CMakeFiles/apache-21287.dir/build
.PHONY : apache-21287/fast

#=============================================================================
# Target rules for targets named apache-25520

# Build rule for target.
apache-25520: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apache-25520
.PHONY : apache-25520

# fast build rule for target.
apache-25520/fast:
	$(MAKE) -f TESTS/apache-25520/CMakeFiles/apache-25520.dir/build.make TESTS/apache-25520/CMakeFiles/apache-25520.dir/build
.PHONY : apache-25520/fast

#=============================================================================
# Target rules for targets named apache-46215

# Build rule for target.
apache-46215: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apache-46215
.PHONY : apache-46215

# fast build rule for target.
apache-46215/fast:
	$(MAKE) -f TESTS/apache-46215/CMakeFiles/apache-46215.dir/build.make TESTS/apache-46215/CMakeFiles/apache-46215.dir/build
.PHONY : apache-46215/fast

#=============================================================================
# Target rules for targets named apache-2.4.18

# Build rule for target.
apache-2.4.18: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apache-2.4.18
.PHONY : apache-2.4.18

# fast build rule for target.
apache-2.4.18/fast:
	$(MAKE) -f TESTS/apache-2.4.18/CMakeFiles/apache-2.4.18.dir/build.make TESTS/apache-2.4.18/CMakeFiles/apache-2.4.18.dir/build
.PHONY : apache-2.4.18/fast

#=============================================================================
# Target rules for targets named mysql-24988

# Build rule for target.
mysql-24988: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql-24988
.PHONY : mysql-24988

# fast build rule for target.
mysql-24988/fast:
	$(MAKE) -f TESTS/mysql-24988/CMakeFiles/mysql-24988.dir/build.make TESTS/mysql-24988/CMakeFiles/mysql-24988.dir/build
.PHONY : mysql-24988/fast

#=============================================================================
# Target rules for targets named mysql-35589

# Build rule for target.
mysql-35589: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql-35589
.PHONY : mysql-35589

# fast build rule for target.
mysql-35589/fast:
	$(MAKE) -f TESTS/mysql-35589/CMakeFiles/mysql-35589.dir/build.make TESTS/mysql-35589/CMakeFiles/mysql-35589.dir/build
.PHONY : mysql-35589/fast

#=============================================================================
# Target rules for targets named memcached-1.4.25

# Build rule for target.
memcached-1.4.25: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memcached-1.4.25
.PHONY : memcached-1.4.25

# fast build rule for target.
memcached-1.4.25/fast:
	$(MAKE) -f TESTS/memcached-1.4.25/CMakeFiles/memcached-1.4.25.dir/build.make TESTS/memcached-1.4.25/CMakeFiles/memcached-1.4.25.dir/build
.PHONY : memcached-1.4.25/fast

#=============================================================================
# Target rules for targets named ssdb-1.9.2

# Build rule for target.
ssdb-1.9.2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssdb-1.9.2
.PHONY : ssdb-1.9.2

# fast build rule for target.
ssdb-1.9.2/fast:
	$(MAKE) -f TESTS/ssdb-1.9.2/CMakeFiles/ssdb-1.9.2.dir/build.make TESTS/ssdb-1.9.2/CMakeFiles/ssdb-1.9.2.dir/build
.PHONY : ssdb-1.9.2/fast

#=============================================================================
# Target rules for targets named mongoose-3.6

# Build rule for target.
mongoose-3.6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mongoose-3.6
.PHONY : mongoose-3.6

# fast build rule for target.
mongoose-3.6/fast:
	$(MAKE) -f TESTS/mongoose-3.6/CMakeFiles/mongoose-3.6.dir/build.make TESTS/mongoose-3.6/CMakeFiles/mongoose-3.6.dir/build
.PHONY : mongoose-3.6/fast

#=============================================================================
# Target rules for targets named linux-4.4.1

# Build rule for target.
linux-4.4.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linux-4.4.1
.PHONY : linux-4.4.1

# fast build rule for target.
linux-4.4.1/fast:
	$(MAKE) -f TESTS/linux-4.4.1/CMakeFiles/linux-4.4.1.dir/build.make TESTS/linux-4.4.1/CMakeFiles/linux-4.4.1.dir/build
.PHONY : linux-4.4.1/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Inst2Int"
	@echo "... CDG"
	@echo "... SyncLoop"
	@echo "... DOL"
	@echo "... ConAnalysis"
	@echo "... libsafe-cve-1125"
	@echo "... libvirt-cve-1447"
	@echo "... apache-21287"
	@echo "... apache-25520"
	@echo "... apache-46215"
	@echo "... apache-2.4.18"
	@echo "... mysql-24988"
	@echo "... mysql-35589"
	@echo "... memcached-1.4.25"
	@echo "... ssdb-1.9.2"
	@echo "... mongoose-3.6"
	@echo "... linux-4.4.1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

